# Generated by Django 3.2.5 on 2021-08-01 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_customers_mobile_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='mobile_number',
            field=models.CharField(max_length=12),
        ),
    ]
