# Generated by Django 3.2.5 on 2021-08-01 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_customers_mobile_number'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Icon',
        ),
    ]
