# Generated by Django 3.2.5 on 2021-08-08 13:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_delete_icon'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=20)),
                ('mobile', models.CharField(max_length=12)),
                ('address', models.TextField(max_length=50)),
                ('city', models.CharField(max_length=20)),
                ('state', models.CharField(max_length=20)),
                ('pin', models.BigIntegerField()),
                ('email', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='store.customers')),
            ],
        ),
    ]
