# Generated by Django 3.2.5 on 2021-08-11 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_auto_20210810_1528'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='quantiy',
            new_name='quantity',
        ),
    ]
