# Generated by Django 3.2.5 on 2021-08-11 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_rename_quantiy_orders_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='status',
            field=models.BooleanField(default=0),
        ),
    ]
