# Generated by Django 3.2.5 on 2021-08-13 08:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_rename_status_orders_delivered'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='customer',
            field=models.ForeignKey(default=56, on_delete=django.db.models.deletion.CASCADE, to='store.customers'),
        ),
    ]
